### ISSUE TITLE
problem: predictions fail for ipv4 prefixes

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/verbose-robot#21]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/csirtg_ipsml_tf/utils.py", line 30, in extract_features
    indicator = int(ipaddress.ip_address(indicator))
  File "/usr/lib/python3.5/ipaddress.py", line 54, in ip_address
    address)
ValueError: '146.185.222.0/24' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/verbose_robot-4.0.0a7+18.g2bd2785-py3.5.egg/cif/gatherer/__init__.py", line 122, in process
    indicators = self.predict_ips(indicators)
  File "/usr/local/lib/python3.5/dist-packages/verbose_robot-4.0.0a7+18.g2bd2785-py3.5.egg/cif/gatherer/__init__.py", line 91, in predict_ips
    f = list(extract_features_ip(i[0].indicator, i[0].reported_at))
  File "/usr/local/lib/python3.5/dist-packages/csirtg_ipsml_tf/utils.py", line 32, in extract_features
    indicator = int(ipaddress.ip_address(indicator.decode('utf-8')))
AttributeError: 'str' object has no attribute 'decode'
2018-08-20 17:44:52,206 - ERROR - cif.gatherer[124][MainThread] - predictions failed
2018-08-20 17:44:52,207 - ERROR - cif.gatherer[125][MainThread] - 'str' object has no attribute 'decode'
```

**Comment by wesyoung** [comment]
test with sans prefix feed
