### ISSUE TITLE
problem: hunter TypeError: unknown itype for

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/verbose-robot#70]
```
2019-04-26 16:38:22,917 - DEBUG - cif.router[199][MainThread] - handling message: indicators_search
2019-04-26 16:38:22,918 - ERROR - tornado.general[441][MainThread] - Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/verbose_robot-4.0a21-py3.6.egg/cif/hunter/__init__.py", line 114, in _process_message
    tlp='amber',
  File "/usr/local/lib/python3.6/site-packages/csirtg_indicator/__init__.py", line 34, in __init__
    self.indicator = indicator
  File "/usr/local/lib/python3.6/site-packages/csirtg_indicator/wrappers/properties.py", line 29, in indicator
    self.itype = resolve_itype(i)
  File "/usr/local/lib/python3.6/site-packages/csirtg_indicator/utils/__init__.py", line 121, in resolve_itype
    raise TypeError(error)
TypeError: unknown itype for "18.5.4.0/8"
2019-04-26 16:38:22,942 - ERROR - tornado.general[468][MainThread] - Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/verbose_robot-4.0a21-py3.6.egg/cif/hunter/__init__.py", line 114, in _process_message
    tlp='amber',
  File "/usr/local/lib/python3.6/site-packages/csirtg_indicator/__init__.py", line 34, in __init__
    self.indicator = indicator
  File "/usr/local/lib/python3.6/site-packages/csirtg_indicator/wrappers/properties.py", line 29, in indicator
    self.itype = resolve_itype(i)
  File "/usr/local/lib/python3.6/site-packages/csirtg_indicator/utils/__init__.py", line 121, in resolve_itype
    raise TypeError(error)
TypeError: unknown itype for "18.5.4.0/8"
2019-04-26 16:38:22,944 - ERROR - asyncio[1285][MainThread] - Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
```

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/silver-meme/pull/26
